version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8989
        --access-logfile -
        --reload
        "watt_app.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/watt_app'
    ports:
      - '8989:8989'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

volumes:
  redis:
